-- Create the tables

CREATE TABLE players (
    id bigint generated by default as identity primary key,
    name text not null
);

CREATE TABLE categories (
    id bigint generated by default as identity primary key,
    name text not null
);

CREATE TABLE words (
    id bigint generated by default as identity primary key,
    word text not null,
    clue text not null,
    category_id bigint references categories (id) not null
);

CREATE TABLE scores (
    id bigint generated by default as identity primary key,
    player_id bigint references players (id) not null,
    time integer not null,
    category_id bigint references categories (id) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert the data

INSERT INTO categories (id, name) VALUES
(1, 'Animales'),
(2, 'Comida'),
(3, 'Deportes'),
(4, 'Países'),
(5, 'Ciencia');

-- Animales
INSERT INTO words (word, clue, category_id) VALUES
('gato', 'Felino doméstico', 1),
('perro', 'Mejor amigo del hombre', 1),
('leon', 'Rey de la selva', 1),
('tigre', 'Felino rayado', 1),
('elefante', 'Mamífero con trompa', 1);

-- Comida
INSERT INTO words (word, clue, category_id) VALUES
('pan', 'Alimento básico de harina', 2),
('arroz', 'Cereal básico en Asia', 2),
('pasta', 'Comida italiana', 2),
('pizza', 'Plato italiano con queso y tomate', 2),
('hamburguesa', 'Carne entre dos panes', 2);

-- Deportes
INSERT INTO words (word, clue, category_id) VALUES
('futbol', 'Deporte de 11 jugadores', 3),
('baloncesto', 'Deporte de canastas', 3),
('voleibol', 'Deporte de red y pelota', 3),
('tenis', 'Deporte de raqueta', 3),
('golf', 'Deporte de palos y hoyos', 3);

-- Países
INSERT INTO words (word, clue, category_id) VALUES
('mexico', 'País de los tacos', 4),
('españa', 'País de la paella', 4),
('argentina', 'País del tango', 4),
('colombia', 'País del café', 4),
('peru', 'País de Machu Picchu', 4);

-- Ciencia
INSERT INTO words (word, clue, category_id) VALUES
('atomo', 'Partícula fundamental', 5),
('electron', 'Partícula subatómica negativa', 5),
('proton', 'Partícula subatómica positiva', 5),
('neutron', 'Partícula subatómica sin carga', 5),
('nucleo', 'Centro del átomo', 5);